-- Load demo.wasm (copied into the server's user_files directory) and register
-- its functions.
INSERT INTO system.webassembly_modules (name, code) VALUES ('cwc_demo', file('demo.wasm'));

CREATE OR REPLACE FUNCTION demo_repeat LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (s String, n UInt32) RETURNS String ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_parse_uint LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (s String) RETURNS Nullable(Int64) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_array_mean LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (xs Array(Float64)) RETURNS Float64 ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_split LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (s String, sep String) RETURNS Array(String) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_divmod LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (a Int64, b Int64) RETURNS Tuple(Int64, Int64) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_tuple_sum LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (t Tuple(Int64, Float64)) RETURNS Float64 ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_flatten LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (xss Array(Array(Int64))) RETURNS Array(Int64) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_upper_all LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (xs Array(Nullable(String))) RETURNS Array(Nullable(String)) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_map_get LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (m Map(String, Int64), k String) RETURNS Nullable(Int64) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_map_invert LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (m Map(String, Int64)) RETURNS Map(Int64, String) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_describe LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (v Variant(Int64, String)) RETURNS String ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_classify LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (s String) RETURNS Variant(Int64, String) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_show_nullable LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (v Nullable(Int64)) RETURNS String ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_halves LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (v Int64) RETURNS Nullable(Tuple(Int64, Int64)) ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_uuid_bytes LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (u UUID) RETURNS String ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_lc_fixed LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (s LowCardinality(FixedString(3))) RETURNS String ABI COLUMNAR_V1 DETERMINISTIC;

CREATE OR REPLACE FUNCTION demo_lc_double LANGUAGE WASM FROM 'cwc_demo'
ARGUMENTS (v LowCardinality(UInt32)) RETURNS UInt64 ABI COLUMNAR_V1 DETERMINISTIC;
